### ISSUE TITLE
DataGrid "Simple Filter Mode with Menu" header styling proposal

### ISSUE THREAD

**Issue by Nephim** [radzenhq/radzen-blazor#1586]
## **The problem**
I am of the opinion that the DataGrid's "Simple Filter Mode with Menu" is the nicest way to do filtering. However I feel like the CSS could use some improvements when the column width becomes small.

![billede](https://github.com/radzenhq/radzen-blazor/assets/39805658/c85c45f5-6609-40de-9bcf-de7cd16cf36f)

In my opinion there is a lot of "wasted space" here.

## **My idea**
So I got to thinking that maybe a container query that would activate when the column width is below 100px (or some other value) and then collapse the input.

The first thing you could do:

```css
.rz-filter-button .rzi {
   display: none;
}
```

![billede](https://github.com/radzenhq/radzen-blazor/assets/39805658/b66f8590-a2ad-469b-9a19-d39153f7818e)

However this can also be taken a lot further:

```css
.rz-filter-button {
   position: absolute;
   min-width: unset;
   margin-left: 0.2rem;
   z-index: 100;
   border-radius: 80%;
}

.rz-filter-button .rz-spinner-input {
   text-indent: 24px; /* A variable should probably be used here */
}
```

![billede](https://github.com/radzenhq/radzen-blazor/assets/39805658/e44b9779-d84b-4e69-8c40-636aaf11ca63)

## **My questions for you!**

Is this something that you find interesting? 
Should I attempt a PR?
Which iteration is the best?
Do you have a better idea or improvements?

**Comment by Nephim** [comment]
I have made a POC for it:

![firefox_bDpLILM4iF](https://github.com/radzenhq/radzen-blazor/assets/39805658/e58e88a5-7cc8-423f-a384-61f464071b0b)

Here is the code for it:

```css
.rz-cell-filter-content {
  container-type: inline-size;
}

@container (max-width: 200px) {
  .rz-cell-filter-content .rz-filter-button .rzi {
    display: none;
  }
  .rz-cell-filter-content .rz-filter-button {
    min-width: 2rem;
    min-height: 90%;
    margin: unset;
    border-radius: 50%;
    padding: unset;
  }
  .rz-cell-filter-content .rz-cell-filter-label {
    border: var(--rz-input-border);
    border-radius: var(--rz-input-border-radius);
    box-shadow: var(--rz-input-shadow);
    background-color: var(--rz-input-background-color);
    height: var(--rz-input-height) !important;
    display: flex;
    gap: 4px;
    align-items: center;
    padding: 0 4px;
  }
  .rz-cell-filter-content .rz-cell-filter-label:hover
  {
    box-shadow: var(--rz-input-hover-shadow);
    border: var(--rz-input-hover-border);
  }
  .rz-cell-filter-label:has(input:focus) {
    box-shadow: var(--rz-input-focus-shadow) !important;;
    border: var(--rz-input-focus-border) !important;;
    outline: var(--rz-input-focus-outline) !important;;
    outline-offset: var(--rz-input-focus-outline-offset) !important;;
  }
  .rz-cell-filter-content .rz-cell-filter-label .rz-inputtext,
  .rz-cell-filter-content .rz-cell-filter-label .rz-spinner, 
  .rz-cell-filter-content .rz-cell-filter-label .rz-textbox {
    border: none !important;
    outline: none;
    box-shadow: none !important;
    background: unset;
  }
  
  .rz-cell-filter-content .rz-cell-filter-label .rz-textbox,
  .rz-cell-filter-content .rz-cell-filter-label .rz-spinner-input,
  .rz-cell-filter-content .rz-cell-filter-label .rz-spinner {
    padding: unset;
  }
}
```

I have tested it on all the themes on the [Radzen website](https://blazor.radzen.com/datagrid-simple-filter-menu)
