### ISSUE TITLE
SelectBar background colour formatting 

### ISSUE THREAD

**Issue by paritoshromy** [radzenhq/radzen-blazor#1656]
It will be good if we can specify the background colour for selected and unselected bar item. Also the button style.

**Comment by yordanov** [comment]
You can adjust background and text colors via CSS variables. Here is an example:

```css
<RadzenSelectBar @bind-Value=@value TValue="bool" class="my-warning-selectbar">
    <Items>
        <RadzenSelectBarItem Text="On" Value="true" />
        <RadzenSelectBarItem Text="Off" Value="false" />
    </Items>
</RadzenSelectBar>

<style>
    .my-warning-selectbar {
        --rz-selectbar-background-color: var(--rz-warning-lighter);
        --rz-selectbar-color: var(--rz-on-warning-lighter);
        --rz-selectbar-selected-background-color: var(--rz-warning);
        --rz-selectbar-selected-color: var(--rz-on-warning);
    }
</style>

@code {
    bool value;
}
```

@paritoshromy, does this resolve the issue?
