### ISSUE TITLE
Scheduler Planner and Timeline view z-index

### ISSUE THREAD

**Issue by w3ori** [radzenhq/radzen-blazor#1815]
**Describe the bug**
I use RadzenScheduler and when I try to edit an event on Planner or Timeline view, then the months and headers came in the foreground because of `z-index`.

**To Reproduce**
1. I worked like the secont example here: https://blazor.radzen.com/scheduler?theme=material3
2. I don't know how it can work on the example page, beacause the z indexes are the same and the dialog has lower z index than the headers.

**Expected behavior**
Don't bring the months and headers in the foreground.

**My workaround**
```css
.rz-view-header {
    z-index: 999 !important;
}

.rz-month .rz-slot:first-child {
    z-index: 999 !important;
}
```

**Screenshots**
Example
![image](https://github.com/user-attachments/assets/2b826337-754a-4b7c-a3fd-08718d3f6169)
![image](https://github.com/user-attachments/assets/f402f907-97ec-44d3-bda7-439cdbcdbdb4)
![image](https://github.com/user-attachments/assets/8cdf6838-01d3-486b-995b-05aabcd35f75)

My
![image](https://github.com/user-attachments/assets/2909afac-d5e9-4a51-8754-76d24d632396)

**Desktop:**
 - OS: WIN 11
 - Browser: Chrome
 - Version: 5.6.7
