### ISSUE TITLE
Scheduler | MaxAppointmentsInSlot overflow

### ISSUE THREAD

**Issue by w3ori** [radzenhq/radzen-blazor#1869]
**Describe the bug**
Events overflows in a day.

**To Reproduce**
1. Go to 'https://blazor.radzen.com/scheduler?theme=material'
2. Click on EditSource
3. Add  `<RadzenMonthView MaxAppointmentsInSlot="5" />`
4. Click on Run
5. Add more than 5 events on a day

**Expected behavior**
Make day cells bigger to fit elements defined in `MaxAppointmentsInSlot`.

**Screenshots**
![image](https://github.com/user-attachments/assets/6b26e428-d9e2-4b65-aefb-8ea4e0a876f9)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser chrome
 - Version 5.7

**Comment by akorchev** [comment]
Indeed the height isn't expanded at the moment. Even if it were expanded the last row wouldn't be entirely visible. We will investigate for possible ways to improve that.

There is a workaround though:

```css
<style>
    .rz-month-view .rz-view-content {
        overflow: auto;
    }
    .rz-month-view .rz-week {
       height: calc(1.5rem * 5 + 2*1.5rem); /* 5 slots each 1.5rem tall + two extra rows - one for the title and one for the "+ x more" button */
    }
</style>
```
