### ISSUE TITLE
RadzenDatePicker: calendar popup click target needs to be bigger, or perhaps show calendar always when focused

### ISSUE THREAD

**Issue by szalapski** [radzenhq/radzen-blazor#254]
**Is your feature request related to a problem? Please describe.**
The date picker (calendar) popup is the primary way users have to choose a date, yet opening it has a very small click target. Clicks (or taps) in the margin or padding near it, or in the empty space between the displayed date and the calendar  button, results in nothing happening when the user is trying to open the calendar date picker.  Additionally, the positioning/layout DOM structure for this button seems quite complicated and it isn't easy to override styles to have the desired effect.

**Describe the solution you'd like**
Clicking in the padding around the button or in the empty space in the middle should open the date picker calendar popup.  Only clicking directly on the date text would select it without opening.

Another approach might be to provide a parameter, something like `bool ShowCalendarWhenFocused`, to enable a click anywhere in the entire collapsed control to open the date picker (calendar) popup.  **This is simpler and perhaps what I would prefer.**  

**Describe alternatives you've considered**
I tried customizing the CSS, but was stymied the layout complexity.  I ended up doing this, which is inadequate but at least makes the click target just a little bigger on its left.  I do not suggest you use this CSS, I am just including it for reference what a feeble approach might be.

```css
    .rz-datepicker-trigger {
        right: 1.625rem; // overrides default .625rem by an extra 1rem to make room for padding-left
        padding-left: 1rem; // for larger click target
    }
```
