### ISSUE TITLE
new component RadzenOverlay

### ISSUE THREAD

**Issue by chrgraefe** [radzenhq/radzen-blazor#92]
**Is your feature request related to a problem? Please describe.**

It's a component, which should grey out the whole screen with an overlay until any loading process is in progress.

kind of:
```
<div id="@CssClass">
  <div id="text">@Text</div>
</div>

@code {
    [Parameter]
    public Boolean IsActive { get; set; } = true;

    [Parameter]
    public String Text { get; set; } = "";

    protected string CssClass => IsActive ? "overlayOn" : "overlayOff";
}
```
```CSS
        #overlayOff {
            position: fixed; /* Sit on top of the page content */
            display: none; /* Hidden by default */
            width: 100%; /* Full width (cover the whole page) */
            height: 100%; /* Full height (cover the whole page) */
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: rgba(0,0,0,0.5); /* Black background with opacity */
            z-index: 2; /* Specify a stack order in case you're using a different order for other elements */
            cursor: pointer; /* Add a pointer on hover */
        }

        #overlayOn {
            position: fixed; /* Sit on top of the page content */
            display: block; /* Hidden by default */
            width: 100%; /* Full width (cover the whole page) */
            height: 100%; /* Full height (cover the whole page) */
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: rgba(0,0,0,0.5); /* Black background with opacity */
            z-index: 2; /* Specify a stack order in case you're using a different order for other elements */
            cursor: pointer; /* Add a pointer on hover */
        }

        #text {
            position: absolute;
            top: 50%;
            left: 50%;
            font-size: 50px;
            color: white;
            transform: translate(-50%,-50%);
            -ms-transform: translate(-50%,-50%);
        }
```
